// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v3azure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3azure));
        
        string IMigrationMetadata.Id
        {
            get { return "201311070548291_v3azure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
