// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agregaAccionaVisita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregaAccionaVisita));
        
        string IMigrationMetadata.Id
        {
            get { return "201312041928330_agregaAccionaVisita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
