// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class constructorVisita : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(constructorVisita));
        
        string IMigrationMetadata.Id
        {
            get { return "201310141905005_constructorVisita"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
