// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class eliminareporte : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eliminareporte));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050659102_eliminareporte"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
