// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class agregaboolnotificacliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregaboolnotificacliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050229418_agregaboolnotificacliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
