// <auto-generated />
namespace CVisits.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class quepasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quepasa));
        
        string IMigrationMetadata.Id
        {
            get { return "201312050726477_quepasa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
